version: "3.8"

services:
  data-base:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: photoshare
    ports:
      - 5432:5432
    networks:
      - app_network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app_network

  user:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - PROJECT=user
        - PORT=3001
    restart: always
    networks:
      - app_network
    ports:
      - 3001:3001
    depends_on:
      - data-base
    env_file:
      - .dev.env
  
  auth:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - PROJECT=auth
        - PORT=3000
    restart: always
    networks:
      - app_network
    ports:
      - 3000:3000
    depends_on:
      - data-base
    env_file:
      - .dev.env
networks:
  app_network: