version: "3.8"

services:
  cassandra:
    image: cassandra:5.0
    ports:
      - 9042:9042
    healthcheck:
      test:
        [
          "CMD",
          "cqlsh",
          "-u cassandra",
          "-p cassandra",
          "-e describe keyspaces",
        ]
      interval: 15s
      timeout: 10s
      retries: 10
  cassandra-init:
    image: cassandra:5.0
    volumes:
      - ./cassandra/entrypoint.sh:/entrypoint.sh
    entrypoint: ["/entrypoint.sh"]
    depends_on:
      - cassandra
