version: "3.8"

services:
  data-base:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: photoshare
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080